### ISSUE TITLE
Barba beschränken auf container

### ISSUE THREAD

**Issue by filimoreira** [profitlich-ch/profitlich-vorlage.ch#107]
{% set headers = craft.app.request.getHeaders() %}
{# Alles ausser Barba container weglassen, wenn Anfrage über Barba kommt, für schnelle Anfrage und Übertragung #}
{% if headers.has('x-barba') == false %}

{# Ende x-barba #}
{% endif %}

{% if headers.has('x-barba') == false %}

{# Ende x-barba #}
{% endif %}

**Comment by mprofitlich** [comment]
Globals sind nicht verfügbar, wenn nicht die ganze Seite ausgegeben wird. Dann müssen sie explizit geholt werden:
`{% set companyInfo = craft.app.globals().getSetByHandle('companyInfo') %}`

**Comment by mprofitlich** [comment]
Gelöst durch Wiki-Eintrag zu Barba
