### ISSUE TITLE
macro bild background-color zentral definieren

### ISSUE THREAD

**Issue by filimoreira** [profitlich-ch/profitlich-vorlage.ch#133]
Jetzt muss man es bei jedem Aufruf des Makros angeben. Ziel: ZEntral definieren, am besten in der config.json. Dafür müsste twig die Datei lesen können.

**Comment by filimoreira** [comment]
Auf basis von studioC kopieren

**Comment by mprofitlich** [comment]
Die Datei einzulesen würde Zeit kosten und somit Performance. Es gibt keine weiteren Stellen, an denen wir in Twig die Konfiguration benötigen. Daher wont fix.
