### ISSUE TITLE
CSP gegen Cross Site Scripting

### ISSUE THREAD

**Issue by filimoreira** [profitlich-ch/profitlich-vorlage.ch#25]
https://developer.chrome.com/docs/lighthouse/best-practices/csp-xss/?utm_source=lighthouse&utm_medium=devtools

**Comment by mprofitlich** [comment]
Dynamische Stile: https://bmt-systems.com/blog/using-dynamic-style-sheets-to-modify-css-with-a-strict-style-src-content-security-policy

Modul für uniqueID: https://craftcms.stackexchange.com/a/29629/13478

**Comment by mprofitlich** [comment]
Base64 Bilder als src="url(data…" funktionieren nicht mit nonces. In der CSP datazu erlauben wäre ein Risiko, daher ist es nach aktuellem Stand nicht möglich, Bilder auf die Art einzufügen. Ich eröffne dazu ein eigene Issue; vielleicht gibt es später einmal eine Möglichkeit.

siehe #128
