### ISSUE TITLE
Upload mit basic-ftp: binäre Dateien sind kaputt

### ISSUE THREAD

**Issue by filimoreira** [profitlich-ch/profitlich-vorlage.ch#253]

**Comment by mprofitlich** [comment]
Gulp behandelt Dateien per default als utf-8. Mit `encoding: false` werden die Dateien als Binärdateien behandelt.
```
return src(files.uploadWeb.src, { encoding: false })
```

**Comment by mprofitlich** [comment]
fixed by 708c81bb6218ced5daf900d2556a222863c5dea9
