### ISSUE TITLE
Macro für Videos anlegen

### ISSUE THREAD

**Issue by mprofitlich** [profitlich-ch/profitlich-vorlage.ch#75]
Grundlage kann das Projekt Cyan Website sein (Baustein Projekt)

**Comment by filimoreira** [comment]
Container auf overflow: hidden, so dass Zoom (transform: scale) möglich ist.

**Comment by mprofitlich** [comment]
Option für Video src per Skript setzen anlegen. Sollen die Videos beim Neuladen der Seite wechseln, klappt das sonst im Firefox nicht, er lädt trotz geänderter src den Inhalt des iframe aus dem Cache.

Kopieren aus CYA Baustein startseite
